# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Major Courses\DataBase\lab\LAB2\LAB2-code\CAAC.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Ui_insert_new_flight import InsertFlight
from ui_delete_flight import DeleteFlight
from ui_table import table
import pymysql
import pandas as pd
from ui_greaterthann import GreaterThanN
class CAAC(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1500, 657)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(150, 90, 1000, 71))
        self.textEdit.setObjectName("textEdit")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton.setGeometry(QtCore.QRect(420, 250, 186, 41))
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.commandLinkButton_2 = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton_2.setGeometry(QtCore.QRect(420, 350, 186, 41))
        self.commandLinkButton_2.setObjectName("commandLinkButton_2")
        self.commandLinkButton_3 = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton_3.setGeometry(QtCore.QRect(420, 440, 300, 41))
        self.commandLinkButton_3.setObjectName("commandLinkButton_3")
        self.commandLinkButton_4 = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton_4.setGeometry(QtCore.QRect(420, 540, 700, 41))
        self.commandLinkButton_4.setObjectName("commandLinkButton_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 966, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.commandLinkButton.clicked.connect(self.insert)
        self.commandLinkButton_2.clicked.connect(self.delete)
        self.commandLinkButton_3.clicked.connect(self.query)
        self.commandLinkButton_4.clicked.connect(self.greaterthann)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; font-weight:600;\">尊敬的工作人员，请选择事项：</span></p></body></html>"))
        self.commandLinkButton.setText(_translate("MainWindow", "新增航班"))
        self.commandLinkButton_2.setText(_translate("MainWindow", "删除航班"))
        self.commandLinkButton_3.setText(_translate("MainWindow", "查询有外航驻扎机场"))
        self.commandLinkButton_4.setText(_translate("MainWindow", "查询驻扎机场数量大于n航司代码"))


    def insert(self):
        self.window=QtWidgets.QMainWindow()
        self.i=InsertFlight()
        self.i.setupUi(self.window)
        self.window.show()

    def delete(self):
        self.window=QtWidgets.QMainWindow()
        self.d=DeleteFlight()
        self.d.setupUi(self.window)
        self.window.show()
    
    def greaterthann(self):
        self.window=QtWidgets.QMainWindow()
        self.d=GreaterThanN()
        self.d.setupUi(self.window)
        self.window.show()
    #分组查询
    def query(self):
        con = pymysql.connect(host='localhost', port=3306, user='root', password='000000', charset='utf8',database='airlines')  # 连接数据库
        sql=f"select aname from (select aname,company.IATA,ctype from stationed natural join company where ctype='外企') as companyandairport group by aname having count(IATA)>0"
        df=pd.read_sql(sql,con)
        self.form=QtWidgets.QWidget()
        self.table=table()
        self.table.setupUi(self.form,len(df),len(df.columns),[x for x in range(1,len(df)+1)],["机场名称"])
        for i in range(len(df)):
            for j in range(len(df.columns)):
                self.table.tableWidget.setItem(i, j, QtWidgets.QTableWidgetItem(str(df.iat[i,j]).strip()))
        self.form.show()
        con.close()

    
