# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Major Courses\DataBase\lab\LAB2\LAB2-code\delete_flight.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pymysql
import pandas as pd
from PyQt5.QtWidgets import QMessageBox
class DeleteFlight(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1110, 798)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(280, 190, 561, 61))
        self.textEdit.setObjectName("textEdit")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(420, 380, 301, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton.setGeometry(QtCore.QRect(480, 540, 186, 41))
        self.commandLinkButton.setObjectName("commandLinkButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1110, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.commandLinkButton.clicked.connect(self.delete)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; font-weight:600;\">请输入航班号</span></p></body></html>"))
        self.commandLinkButton.setText(_translate("MainWindow", "确认"))
    
    #这里条件判断实现触发器，消除了所有外键引用
    def delete(self):
        fno=self.lineEdit.text()
        #空值约束
        if fno=="":
            self.window=QtWidgets.QMainWindow()
            QMessageBox.warning(self.window,"ERROR","请输入非空值")
        else:
            con = pymysql.connect(host='localhost', port=3306, user='root', password='000000', charset='utf8',database='airlines')  # 连接数据库
            sql=f"select fno from flight where fno='{fno}'"
            df=pd.read_sql(sql,con)
            if len(df)==0:
                self.window=QtWidgets.QMainWindow()
                QMessageBox.warning(self.window,"useless","无该航班，无需删除")
            else:
                #外键约束，先删外键，再删主键
                cur=con.cursor()
                cur.execute(f"delete from takeoff where fno='{fno}'")
                cur.execute(f"delete from landon where fno='{fno}'")
                cur.execute(f"delete from setup where fno='{fno}'")
                cur.execute(f"delete from ttf where fno='{fno}'")
                cur.execute(f"delete from control where fno='{fno}'")
                cur.execute(f"delete from execute where fno='{fno}'")
                cur.execute(f"delete from flight where fno='{fno}'")
                con.commit()
                self.window=QtWidgets.QMainWindow()
                QMessageBox.information(self.window,"success","已经成功删除航班，并删除所有引用该航班的信息")
                cur.close()
                con.close()

