# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Major Courses\DataBase\lab\LAB2\LAB2-code\table.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class table(object):
    def setupUi(self, Form,row,col,rowlist,collist):
        Form.setObjectName("Form")
        Form.resize(864, 549)
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(20, 30, 841, 481))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(col)
        self.tableWidget.setRowCount(row)
        
        for i in range(row):
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setVerticalHeaderItem(i, item)
        for j in range(col):
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setHorizontalHeaderItem(j, item)
        
        self.retranslateUi(Form,rowlist,collist)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form,rowlist,collist):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "结果"))
        for n,i in enumerate(rowlist):
            item = self.tableWidget.verticalHeaderItem(n)
            item.setText(_translate("Form", str(i)))
        for m,j in enumerate(collist):
            item = self.tableWidget.horizontalHeaderItem(m)
            item.setText(_translate("Form", str(j)))